### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by cvionis** [cvionis/notes-cli#2]
- [x] Fix incorrect malloc() syntax
- [x] Free up memory after variables are given dynamically allocated memory
- [ ] Implement error handling during MySQL query
- [x] Investigate why large field entries are causing the field buffers to not be saved in the db

**Comment by cvionis** [comment]
### Task Organization with Functions Outline

- **Creating and Freeing the Note Creation Form and Its Window:** Create separate file for different functions that make up the creation and deletion of form: _form_functions.h_ and _form_functions.c_. Inside the _form_functions_ files, define and implement functions such as "create_form()", "create_form_win()", "free_form_win()", etc. Include these files in _ncurses_utilities.c_. Inside _ncurses_utilities.c_ , use the functions from the included file in a single function named "create_note_form_win()" or something similar.  The latter function will be used in the _main.c_ file. NOTE: You need to determine the arguments that will need to be passed among all these functions.
